In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [3]:
B = np.random.rand(3,3)

B

array([[0.96241469, 0.21345761, 0.24709118],
       [0.61771645, 0.14398761, 0.00851115],
       [0.59499966, 0.66466855, 0.84388019]])

In [5]:
A + B

array([[ 1.96241469, -0.78654239,  2.24709118],
       [ 3.61771645,  2.14398761,  2.00851115],
       [ 4.59499966,  1.66466855,  2.84388019]])

In [6]:
A * 5

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [7]:
np.dot(A, B)

array([[1.53469756, 1.39880711, 1.9263404 ],
       [5.31267628, 2.25768516, 2.44605621],
       [5.65737452, 2.32715516, 2.68463623]])

In [9]:
A @ B

array([[1.53469756, 1.39880711, 1.9263404 ],
       [5.31267628, 2.25768516, 2.44605621],
       [5.65737452, 2.32715516, 2.68463623]])

In [10]:
A @ B + (A + 2 * B)

array([[ 4.45952693,  0.82572232,  4.42052275],
       [ 9.54810918,  4.54566039,  4.46307852],
       [10.84737384,  4.65649227,  6.37239661]])

# 실습 과제

In [11]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

In [12]:
result = 2*A @ (-1*B) @ (3*C + D)

result

array([[  34,  -28],
       [ 110, -130]])