In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2],
    [7,5,6]   
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0,1],
    [-1,3],
    [5,2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [4]:
C = np.random.rand(3,5) #0~1 사이의 랜덤한 값을 가지는 3x5 행렬

C

array([[0.41702738, 0.92421313, 0.82907123, 0.50240124, 0.78373271],
       [0.54654285, 0.28897917, 0.33824117, 0.70157274, 0.53361711],
       [0.58480627, 0.19628326, 0.83020085, 0.62482377, 0.85600243]])

In [6]:
D = np.zeros((2, 4)) #모든 원소값이 0인 2x4 행렬

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [9]:
A[0][2]

2

# 실습 과제

In [10]:
A = np.array([
    [0,1,-1],
    [1,2,3],
    [2,1,0],
    [-1,2,-4]
])

A

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2, -4]])

In [11]:
B = np.array([
    [0,2],
    [1,1],
    [-1,-2]
])

B

array([[ 0,  2],
       [ 1,  1],
       [-1, -2]])

In [12]:
A[1][1]

2

In [13]:
A[3][0]

-1